defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: hipsterscore_development

test:
  <<: *defaults
  database: hipsterscore_test

# set these environment variables on your prod server
production:
  host: flame.mongohq.com
  port: 27077
  database: hipster_score
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
